

server:
  port: 8081
spring:
  application:
      name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mydb01?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.leyou.example.userservicedemo.entity

eureka:
  client:
     service-url:
      defaultZone: http://120.77.219.194:10089/eureka
